name: Addition of Two Numbers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2 
      with:
        python-version: 3.9
      
    - name: Run Python code
      run: python add.py
    
    - name: Set up self-hosted runner
      uses: actions/runner/setup@v2
      with:
        runner-type: self-hosted
        repository: blackorder11/Actions
        label: My_Self_Hosted_Runner
        token: ${{ secrets.GITHUB_TOKEN }}
