name: Addition of Two Numbers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [My_Self_Hosted_Runner]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2 
      with:
        python-version: 3.9
      
    - name: Run Python code
      run: python add.py
